version: "3.5"
services:
  
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'seucandidato'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 3306:3306

    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: