version: "3.5"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_DB: 'seucandidato'
    ports:
      - 3306:3306

    volumes:
      - my-db:/var/lib/mysql